---
name: GPI_2
board: boards/red-pitaya
version: 0.1.1

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - instruments/GPI_3/cores/data_collector_v1_0
  - instruments/GPI_3/cores/outputs_v1_0
  - instruments/GPI_3/cores/trig_delay_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: dac
    offset: '0x40000000'
    range: 32K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - led
  - GPI_safe_state
  - slow_1_trigger
  - slow_2_trigger
  - slow_3_trigger
  - slow_4_trigger
  - fast_1_trigger
  - fast_1_permission
  - fast_1_duration
  - fast_2_trigger
  - fast_2_permission
  - fast_2_duration
  - reset_time


status_registers:
  - adc[n_adc]
  - W7X_timings
  - abs_gauge
  - diff_gauge
  - slow_1_trigger_sts
  - slow_2_trigger_sts
  - slow_3_trigger_sts
  - slow_4_trigger_sts

parameters:
  fclk0: 166666667
  bram_addr_width: 13
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/GPI_3/expansion_connector.xdc


drivers:
  - ./GPI_2.hpp
  - server/drivers/common.hpp

# web:
#   - web/koheron.ts
#   - web/jquery.flot.d.ts
#   - ./web/pulse_generator.ts
#   - ./web/app.ts
#   - ./web/control.ts
#   - ./web/plot.ts
#   - ./web/index.html
#   - web/main.css
#   - web/navigation.ts
