---
name: GPI_RP
board: boards/red-pitaya
version: 0.1.1

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - instruments/GPI_RP/cores/data_collector_v1_0
  - instruments/GPI_RP/cores/outputs_v1_0
  - instruments/GPI_RP/cores/trig_delay_v1_0
  - instruments/GPI_RP/cores/split_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: dac
    offset: '0x40000000'
    range: 32K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K
  - name: xadc
    offset: '0x30000000'
    range: 64K

control_registers:
  - led
  - GPI_safe_state
  - slow_1_manual
  - slow_2_manual
  - slow_3_manual
  - slow_4_manual
  - fast_manual
  - fast_permission_1
  - fast_permission_2
  - fast_delay_1
  - fast_delay_2
  - fast_duration_1
  - fast_duration_2
  - send_T1
  - reset_time
  - analog_out

status_registers:
  - adc[n_adc]
  - W7X_T1
  - W7X_permission
  - analog_input_0
  - analog_input_1
  - abs_gauge
  - diff_gauge
  - slow_1_sts
  - slow_2_sts
  - slow_3_sts
  - slow_4_sts
  - fast_sts
  - analog_out_sts

parameters:
  fclk0: 166666667
  bram_addr_width: 13
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/GPI_RP/expansion_connector.xdc

drivers:
  - ./GPI_RP.hpp
  - server/drivers/common.hpp
  - server/drivers/xadc.hpp
